### ISSUE TITLE
about training time

### ISSUE THREAD

**Issue by GY56723-debug** [wenj/GoMAvatar#1]
I spend around 3 days to training cap 387 of zju dataset, It's nomal?

**Comment by wenj** [comment]
Could you try to enable the prefetch - setting to True in this line: https://github.com/wenj/GoMAvatar/blob/main/configs/default.yaml#L18?

**Comment by GY56723-debug** [comment]
Thanks, I will try

**Comment by GY56723-debug** [comment]
After I set the prefetch true, it's sim to resume about 30 hours for training. It's all right?

**Comment by wenj** [comment]
I just did a quick try on my side. It took ~17h for training without further optimization in training speed. 

If it is due to slow I/O, you could try to disable tensorboard and logging. Another option is to crop a patch in each iteration by setting crop_size [here](https://github.com/wenj/GoMAvatar/blob/main/configs/default.yaml#L17), e.g. [36, 36]. We didn't explore much to accelerate the training speed upon code releasing. So feel free to try more options!

**Comment by GY56723-debug** [comment]
thanks, I will close the issue

**Comment by yt0409** [comment]
@wenj  could you please tell me how to disable logging and tensorboard? just delete these code or other methods?thanks for your patience. one thing is that i find this model only use 4g gpu memory,but the gpu util is 100%, due to slow I/O？

**Comment by xianrui-luo** [comment]
> I just did a quick try on my side. It took ~17h for training without further optimization in training speed.
> 
> If it is due to slow I/O, you could try to disable tensorboard and logging. Another option is to crop a patch in each iteration by setting crop_size [here](https://github.com/wenj/GoMAvatar/blob/main/configs/default.yaml#L17), e.g. [36, 36]. We didn't explore much to accelerate the training speed upon code releasing. So feel free to try more options!

Hi, using crop_size leads to `RuntimeError: The size of tensor a (512) must match the size of tensor b (36) at non-singleton dimension 2`, also pre_fetch=True does not speed up in my case, I use 3090.

**Comment by wenj** [comment]
For the `crop_size` mismatch, during training, you probably want to set the `img_size` to [36, 36] as well. But remember to change it back to the desired size during inference.

 `prefetch=True` will load all data in advance so that no more data is read from the disk in training. It helps if your I/O is a bottleneck.

To disable tensorboard, you could remove the lines setting up the tensorboard. Meanwhile, feed tb=None (or tb_logger=None) in the model.
